# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\x17\n\x06Number\x12\r\n\x05input\x18\x01 \x01(\x05\"\x19\n\x06Result\x12\x0f\n\x07resulta\x18\x01 \x01(\x05\x32=\n\x11SquareRootService\x12(\n\nSquareRoot\x12\x0c.test.Number\x1a\x0c.test.Resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=20
  _NUMBER._serialized_end=43
  _RESULT._serialized_start=45
  _RESULT._serialized_end=70
  _SQUAREROOTSERVICE._serialized_start=72
  _SQUAREROOTSERVICE._serialized_end=133
# @@protoc_insertion_point(module_scope)
